### ISSUE TITLE
Add a cool readme to this repo

### ISSUE THREAD

**Issue by Souravirus** [Souravirus/scrappers#2]
A good structured readme would be appreciated.

**Comment by stefanmiodrag** [comment]
I could do this, what needs to covered?

**Comment by Souravirus** [comment]
You can add the current contents of the repo.

**Comment by stefanmiodrag** [comment]
Mind giving a short description of what they all do?

**Comment by Souravirus** [comment]
a2ojExtractor extracts the question in the site a2oj.com and saves the html file in the specified folder.
cbse Result checker sees if on that day any new result has come.
resultNITH scraps the results of students of NIT, Hamirpur

**Comment by exler** [comment]
I beautified it a little and added your scrapers descriptions. #5

**Comment by Souravirus** [comment]
Ok @exler I have merged that
