### ISSUE TITLE
Update the readme.md

### ISSUE THREAD

**Issue by Souravirus** [Souravirus/scrappers#6]
Add about the imdb_api and give a beautiful description about it

**Comment by vishnuramana** [comment]
@Souravirus  can I work on this ?

**Comment by Souravirus** [comment]
Yeah please @V1cHu

**Comment by sameerkumar18** [comment]
Added imdb_api description in readme #7

**Comment by Souravirus** [comment]
@sameerkumar18 I have merged that

**Comment by vishnuramana** [comment]
guess this is done then .

**Comment by Souravirus** [comment]
Yeah sorry @V1cHu
